### ISSUE TITLE
Pending Approval

### ISSUE THREAD

**Issue by jasonseminara** [mgershowitz/happy-hour#1]
I love it. How will you be implementing this, technically. 

I'd like to see your draft of a technical specifications (the _how_) to make sure this is feasible for this project.

**Comment by jasonseminara** [comment]
bump.

**Comment by mgershowitz** [comment]
I added some more to the readme. Basically I want to do AJAX calls with query params that will be filtered based on the questionnaire. The quotes are now stored in a mongo collection and are pulled 1 at random.

**Comment by mgershowitz** [comment]
I can't use AJAX so I'm using request
